# Generated by Django 4.0.6 on 2022-08-12 21:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Glucose',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gerat', models.CharField(blank=True, max_length=255)),
                ('serien_nummer', models.CharField(blank=True, max_length=255)),
                ('gerate_zeitstempel', models.DateTimeField(blank=True, null=True)),
                ('auf_zeichnungstyp', models.CharField(blank=True, max_length=255)),
                ('glukosewert_verlauf', models.CharField(blank=True, max_length=255)),
                ('glukose_scan', models.CharField(blank=True, max_length=255)),
                ('nicht_numerisches_schnellwirkendes_insulin', models.CharField(blank=True, max_length=255)),
                ('schnellwirkendes_insulin', models.CharField(blank=True, max_length=255)),
                ('nicht_numerische_nahrungsdaten', models.CharField(blank=True, max_length=255)),
                ('kohlenhydrate_gramm', models.CharField(blank=True, max_length=255)),
                ('kohlenhydrate_portionen', models.CharField(blank=True, max_length=255)),
                ('nicht_numerisches_depotinsulin', models.CharField(blank=True, max_length=255)),
                ('depot_insulin_einheiten', models.CharField(blank=True, max_length=255)),
                ('notizen', models.CharField(blank=True, max_length=255)),
                ('glukose_teststreifen', models.CharField(blank=True, max_length=255)),
                ('keton', models.CharField(blank=True, max_length=255)),
                ('mahlzeiteninsulin_einheiten', models.CharField(blank=True, max_length=255)),
                ('korrekturinsulin_einheiten', models.CharField(blank=True, max_length=255)),
                ('insulin_anderung_durch_anwender_einheiten', models.CharField(blank=True, max_length=255)),
                ('user_id', models.CharField(max_length=255)),
            ],
        ),
    ]
